output: 22101910_FezaEmir_Celik_hw1.o 22101910_FezaEmir_Celik_sorting.o
	g++ 22101910_FezaEmir_Celik_hw1.o 22101910_FezaEmir_Celik_sorting.o -o output

22101910_FezaEmir_Celik_hw1.o: 22101910_FezaEmir_Celik_hw1.cpp
	g++ -c 22101910_FezaEmir_Celik_hw1.cpp

22101910_FezaEmir_Celik_sorting.o: 22101910_FezaEmir_Celik_sorting.cpp 22101910_FezaEmir_Celik_sorting.h
	g++ -c 22101910_FezaEmir_Celik_sorting.cpp

clean:
	rm *.o output